### ISSUE TITLE
zoom in graphs

### ISSUE THREAD

**Issue by tivvit** [gdg-garage/space-tycoon#105]

**Comment by malytomas** [comment]
simple implementation in 7bb46b38f7fa2688c05e8daac792aefc6acfa4d5
it allows to zoom and pan the graph as a whole, instead of focusing on more details.
unfortunately, i do not have time to implement proper zoom now.
i have tried it and it is terrible..

**Comment by malytomas** [comment]
feel free to reopen if you consider the current implementation significantly insufficient..
