### ISSUE TITLE
detail: the user is always equal player in the current implementation

### ISSUE THREAD

**Issue by tivvit** [gdg-garage/space-tycoon#114]
We can hide players as an implementation detail.

**Comment by malytomas** [comment]
every time season changes, players get new ids.

i assume that the problem you are trying to solve is that login is expired every new season, so perhaps we can fix that in a different way?

**Comment by malytomas** [comment]
can you elaborate more on how you image this?

**Comment by tivvit** [comment]
username == player. Do not use player field for login and registration (we can do it on the backend already)

**Comment by malytomas** [comment]
would it be sufficient to make player name optional (and use same as user name) and leave all remaining functionality intact?

**Comment by tivvit** [comment]
yes, that is what I meant (kind of). Maybe a little more than you wish.

It will not be mentioned in the API docs, and it will not be accepted by the server (to simplify things). But the database will remain intact. All will be hidden by the server.

But if you really like it and do not want to change anything, we can just make it optional in the API specs, edit the server accordingly, and do not use it in the example bot.

**Comment by malytomas** [comment]
I think we have more pressing issues than this.

Anyway, I feel like going all in (_merging_ players and users even in the database and everywhere) or just leave it as it is.
Having the distinction made sense for the public/shared testing server, but we have ditched that, so...

**Comment by malytomas** [comment]
I have prepared the necessary changes in the database if you want to pursue this change ...
The branch/pr is yours now.
