### ISSUE TITLE
score over all seasons

### ISSUE THREAD

**Issue by malytomas** [gdg-garage/space-tycoon#122]
- discussion: weighting parameters?
- api (swagger + go)
- visualization: table/graph

**Comment by tivvit** [comment]
weight: linear or quadratic?

I can write the swagger and server part - can you pls prepare the database side?

Is this going to be a part of the reports, or is it something extra? I am not able to decide

**Comment by malytomas** [comment]
It is already done in the database. Table d_user_score.

I think it can go into the /reports api. I will be showing it as a graph in the visualization after all.
