### ISSUE TITLE
shorter seasons

### ISSUE THREAD

**Issue by malytomas** [gdg-garage/space-tycoon#126]
I propose to shorten seasons to 1 hour (3600 ticks per season). 120 seasons for the whole trip.

- allows to observe full implications of changes in bots faster
- makes differences in starting locations more fair
- should be enough time to determine winning bots (except for some potential fuckups)
- less wasted time in case one bot starts absolutely dominating the map

**Comment by curusarn** [comment]
1 hours seems good
