### ISSUE TITLE
waypoints should be invisible for players

### ISSUE THREAD

**Issue by curusarn** [gdg-garage/space-tycoon#21]

**Comment by malytomas** [comment]
i see several options here:

1) waypoints are kept as implementation detail and never leave the server. this has an issue that /data will be reporting current ship commands in two different formats, depending on whether the target is a waypoint or actual object, which makes it more complicated for the bots.

2) waypoints are visible to the player, but are filtered to contain waypoints referenced by their own ships only

3) waypoints have associated owner/creator and can be freely reused by the same player

**Comment by curusarn** [comment]
The dual format is not optimal but any other option imho introduces too much unnecessary complexity.

Also the dual format has to exist anyway because players can use it when sending commands. So it seems okay to have them parse it as well.

That's why 1) seems like the best option to me.

**Comment by tivvit** [comment]
1) sgtm
