### ISSUE TITLE
decommission returns money

### ISSUE THREAD

**Issue by malytomas** [gdg-garage/space-tycoon#26]
should decommission return any money?
something like half of the buy cost multiplied by current life fraction?

@curusarn wrote:
> Hmm, I don't see a reason why not. It can give people ability to change strategy mid game. I don't see any possible abuse because even with getting half your money back it's expensive to do this.

> We might see someone rush to build a "shipyard" and sell their mothership to get a lot of money at once. This assumes that there is a cheap enough "shipyard". And I don't really think we mind people doing this.

I would not like it if you could construct new ships at one planet, buy resources, send the ship elsewhere, sell the resources, and sell the ship with a profit, instead of flying it back.

What to do with the current cargo on the ship?

Should presence of another shipyard be required for the decommission?

**Comment by malytomas** [comment]
also decommission should be a separate command type in the database.

**Comment by curusarn** [comment]
That's a very good concern. But aren't the ships going to be too expensive to allow this? The profit that you can make in a single long distance trade would have to be significantly more than half of the price the ship that performed the costs. 

That being said, I think it makes sense to only allow shipyards to decommission ships that are around. Especially, if we also only allow shipyards to repair other ships.

**Comment by curusarn** [comment]
The cargo of the decommissioned ship should be lost imho. The other variant is to transfer it to the shipyard but that seems quite weird to me.

**Comment by tivvit** [comment]
I like the idea of decommission returning money and limiting it only around shipyards. 

Quick attack significantly crippling all the enemies and then going back to trading sounds like something worth having ;)

**Comment by malytomas** [comment]
Accepted.
No shipyard required.
