### ISSUE TITLE
adding players in new season

### ISSUE THREAD

**Issue by malytomas** [gdg-garage/space-tycoon#30]
allowing additional players to connect to the game "in the middle of a season" can bring significant inbalance into the game.

possible solutions:
- allow registering new players at any time - their new spaceship spawns somewhere
  - newly spawned players ship can greatly hurt some existing players giving unfair advantage to others
  - great for prototyping
- allow registering new players at any time - picks one from pregenerated spaceships
  - pregenerated spaceships are sitting in the game obstructing some areas
  - newly connected player can still hurt some existing players more than others
  - great for prototyping
- have dedicated registration time before the season starts
  - this is the most fair
  - not good for prototyping as it requires to wait for the whole season to finish
  - possible improvement: shorter seasons in the beginning when prototyping is most prominent (as low as 5 mins?) and gradually prolonging the seasons to the full length (1 or 2 hours)
- allow registering new players in specified number of ticks in the beginning of each season
  - fairly fair
  - not good for prototyping
  - same possible improvement as above

... more ideas or thoughts?

**Comment by tivvit** [comment]
I would use "allow registering new players at any time - picks one from pregenerated spaceships" for the test server

For the main server, I would choose a slightly different option - generating 1 player per user each season with pre-generated spaceships. They start playing with the ship when they are ready.

**Comment by malytomas** [comment]
Conclusion: allow registering new players at any time - picks one from pregenerated spaceships

**Comment by malytomas** [comment]
TODO:
colors: use HSV with equally distributed hue  and 100% saturation and value
positions: equally spread on a circle

**Comment by malytomas** [comment]
finished in #99
