### ISSUE TITLE
artificial (static) enemies

### ISSUE THREAD

**Issue by tivvit** [gdg-garage/space-tycoon#32]
I thought it would be nice to have blocked parts of the map - it makes ship distribution harder and may also force huge battles for some narrow passes. 

But navigation would be hard, and it is probably not worth it.

But we may introduce (in later stages of the game) AI, which would guard some parts of the map. Like a turret. This could lead to similar behavior changes

**Comment by malytomas** [comment]
Idea: guard "castle" in the center of the map. Player who destroys the castle instantly wins the game.

Postponed..
