### ISSUE TITLE
Visualization

### ISSUE THREAD

**Issue by tivvit** [gdg-garage/space-tycoon#35]
Do we have some ideas/ wireframes for the UI?

I have it a thought and I would not render all ships (because it would be a mess).

I would just have graphics for
* Empty space
* Planet
* ship 
* Planet with ship

On hover or maybe always when there are multiple resources on one place i would use something like this (with player colors)
![red-heart-like-new-message-bubble-friend-request-quantity-number-notifications-icons-templates-red-heart-like-new-message-bubble-116757908.jpg](https://user-images.githubusercontent.com/3392931/181906244-2f37bbb8-aea7-44af-884f-8d54f6a9a78d.jpg)

On click there should be detailed info about that place (like ship names)

**Comment by malytomas** [comment]
I would prefer something like this:
![any-tracking-device2](https://user-images.githubusercontent.com/18198295/181917904-69eabfb3-8cc5-43a3-aada-e1c28f54907a.jpg)

The planet in the center and the ships around it with the line connecting it signaling that they actually overlap.

In case of multiple ships only the center position can be empty and the ships just around.

**Comment by tivvit** [comment]
I see that is also not bad

**Comment by curusarn** [comment]
I like both approaches. With the second one I would like to see the number of ships with each "bubble".
