### ISSUE TITLE
Historical data (server)

### ISSUE THREAD

**Issue by tivvit** [gdg-garage/space-tycoon#36]
There should be a server which will store all the historical data with timestamps).

This is useful for debugging and analyzing the bots (e.q after night)

Those should be possible to visualize and if we have a play button to display events in high fps (like a movie) it would be perfect.

**Comment by malytomas** [comment]
I suggest to store already finished jsons in the same format as they are send from the api.
- json per season with static data
- json per season with reports (contains all ticks)
- json per tick with dynamic data (with no particular player, but all commands)

That should allow us to reuse all of the visualization code with just a minimum changes.

Do you want to store it in the database or outside?

**Comment by tivvit** [comment]
I agree with what to store.

I was thinking about files, but the database is also not a bad idea. The database could have tick and season as indexes therefore the lookup will be quick. We can store the data as JSON (long text or something like that)?

**Comment by tivvit** [comment]
As you mentioned, we will need some special player (provileged) for this to get all the commands.

**Comment by malytomas** [comment]
> As you mentioned, we will need some special player (privileged) for this to get all the commands.

I thought that only finished seasons would be allowed to access and therefore no login is necessary.
But somehow unifying it with current api endpoints is definitely good idea to consider.
