### ISSUE TITLE
add regen/repair properties to swagger

### ISSUE THREAD

**Issue by malytomas** [gdg-garage/space-tycoon#51]
- passively regenerated life per tick
- repaired life and cost per tick with the repair command

also add repair type of command

**Comment by evamayerova** [comment]
Repair is already supported. What needs to be done regarding regen?

**Comment by malytomas** [comment]
the properties were missing from the ship classes

**Comment by evamayerova** [comment]
So can we close the bug now?

**Comment by malytomas** [comment]
no: it is still missing

**Comment by evamayerova** [comment]
ShipClass object should contain this info 
@tivvit promised to take over this one
