### ISSUE TITLE
omitempty resources

### ISSUE THREAD

**Issue by tivvit** [gdg-garage/space-tycoon#53]
see the origin of the discussion https://github.com/gdg-garage/space-tycoon/pull/40#discussion_r937650690

**Comment by malytomas** [comment]
This indicates that it is omitted in the json right? It is still present in the classes/structs in the generated code?

**Comment by curusarn** [comment]
In Go, the omitted fields are filed with default values (0 for ints/numbers, "" for strings, etc.).

In Python, I would expect the generated code to just not add the missing fields to the object.

If the omitted values are replaced with defaults in all languages (Go style) then I think that using omitempty works. But if some clients end up with fileds being omitted in the objects then I think we should not use "omitempty".

Btw does our swagger spec allow omitted damage and cargo capacity?

**Comment by tivvit** [comment]
https://github.com/go-swagger/go-swagger/issues/1707

**Comment by tivvit** [comment]
Works nicely in the end. Used in https://github.com/gdg-garage/space-tycoon/pull/57

**Comment by malytomas** [comment]
> Works nicely in the end. Used in #57

I would not call that solution "nice". I would call that a dirty workaround. But such is the world we live in...

**Comment by tivvit** [comment]
You need a way to tell if something is present or not. Something like
optional. Pointer works nicely for that. I do not see nullable as a hack at
all. Why do you?

Omitempty is also needed in parts of our api, it is just not great as a
default :/

**Comment by malytomas** [comment]
In swagger you define what is optional or required by listing required things in the _required_ clause.
Changing the semantics of the declarations just to change some behavior in the generated code is wrong.
But the actual issue is in the design of the swagger. Nullable should have been an option of the generator and not part of the document.
