### ISSUE TITLE
unify urls for development and deploy

### ISSUE THREAD

**Issue by malytomas** [gdg-garage/space-tycoon#55]
Currently, I need to have hacked-in url overrides in the visualization client during development, because the default is `https://space-tycoon.garage-trip.cz/api`, which obviously does not exist.

We should unify the server api and a website provider to have same url, so that the api url can always be relative.

Remember that the teams will likely want to use the website while testing their bots on their individual testing servers too.

Possible solutions:
1) the go server will also serve the website
2) add a proxy in front, which would redirect /api to the go server and everything else to some simple http server for the website

Thoughts?

**Comment by tivvit** [comment]
Good point we can serve the web by the server - I do not love it but it is probably the simplest solution for everyone

**Comment by malytomas** [comment]
Another possible solution: have hardcoded api url and have two versions of the website:
- website for development - localhost - the default in this repository
- website that runs on production url and uses production api url
