### ISSUE TITLE
how much starting money?

### ISSUE THREAD

**Issue by malytomas** [gdg-garage/space-tycoon#58]
some thoughts? how many ships and resources should players afford at the beginning?

**Comment by curusarn** [comment]
2M is probably the lowest amount that makes sense. It gives you 6 shippers or 4 haulers (or some combination).

You could also afford one fighter and one hauler which could be an interesting starting strategy against dumb bots with no/bad defense/retreat logic.

**Comment by curusarn** [comment]
10M would also be good.

You could buy pretty much anything except destroyer. 
You get a chance to buy both cargo and attack ships right from the beginning.
You get the game started fast.

**Comment by curusarn** [comment]
Generally, too little starting money slows down the beginning of the game and makes loosing even one ship painful.
We should avoid having so little starting money that the game feels uninteresting from the start.

On the other hand, starting period with less money gives people a better chance to observe what is happening and if their strategies work. This might get harder as the game fills with more and more ships so 

I'm not sure if there are more disadvantages in giving people a lot of starting money.

**Comment by malytomas** [comment]
We could have predefined number of ships of each type given to the player (in addition to some money).
That way players would be guaranteed to always start with something reasonable (at least one cargo ship).
Furthermore, it would make it possible for teams to start writing trading strategies right from the beginning, without caring for buying ships.
Downside is reduced choices for the players.

**Comment by curusarn** [comment]
One downside of having to buy ships is the time required to buy all the starting ships. 
With 10M it would take 30 ticks to buy 30 shippers which seems okay.
With 20M it would take 60 ticks to buy 60 shippers which seems like a lot. But it is also the choice of the player to buy that many cheap ships.
However, for this reason I don't think we want to give players more than 20M of starting money.
 
Starting ships could work.

Maybe we can do something like: 10 shippers + 10M of money
Giving players shippers means that they don't have to spend that much time buying ships and shippers are the cheapest ships so they take "relatively the most" time to buy.
10M gives people enough freedom to have a distinct starting buying strategy.

**Comment by malytomas** [comment]
currently: 1 mothership + 5 shippers + 5M money
