### ISSUE TITLE
player.color inconsistency (api vs db column)

### ISSUE THREAD

**Issue by tivvit** [gdg-garage/space-tycoon#59]
in DB column is tinytext in api it is array of numbers - what is correct?

**Comment by malytomas** [comment]
both are correct.
there is no array in sql, and i do not want to split it into three columns, so i use string.
the api should have three values, each in the range of 0..255 inclusive.

**Comment by malytomas** [comment]
you can serialize the color any way you want. the database does not need to understand it.

**Comment by tivvit** [comment]
ok, thx I would split it into 3 cols but serialization sounds ok too :)
