### ISSUE TITLE
values returned in login etc.

### ISSUE THREAD

**Issue by malytomas** [gdg-garage/space-tycoon#73]
create user ok: status ok, user name
create user bad: status bad, reason
login ok: status ok, user name, player name, player id
login bad: status bad, reason
logout: status ok

teď některý z těch operací hodí 500, některé nějaký jiný kódy etc. s tím nemohu prakticky nic dělat..

**Comment by tivvit** [comment]
500 je interka nejsem si jistej jestli je potreba to zminovat v definici, ale to se proste muze stat kazdemu serveru :(

To ostatni je samozrejme bug

**Comment by tivvit** [comment]
Closing in favour of #78
