### ISSUE TITLE
server gives invalid ids in /data in trade reports

### ISSUE THREAD

**Issue by malytomas** [gdg-garage/space-tycoon#98]
[data1.txt](https://github.com/gdg-garage/space-tycoon/files/9378228/data1.txt)

steps to reproduce:
- nastartovat databázi, spustit sezónu.
- nastartovat server, nechat běžet
- v databázi resetovat sezónu a spawnout hráče
- server si všimne že se změnila sezóna a pokračuje
- počkat až některá loď něco nakoupí

**Comment by tivvit** [comment]
is this issue ongoing?

**Comment by malytomas** [comment]
i think this has been fixed. closing
